on:
  push:
    paths:
      - README.Rmd
      - render_readme.yml

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown","rsoi", "tibble"))'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "github_document")'
      - name: Commit results
        run: |
          git commit README.md -m 'Re-build README.Rmd'
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:master
